spring.application.name=youth-policy-api

server.port=8080

logging.level.org.springframework.security=INFO


spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:tcp://localhost/~/EasyWork
spring.datasource.username=sa
spring.datasource.password=
spring.messages.basename=errors

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MyBatis`
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=org.sungsung.youthpolicy.domain
#always,never
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql


#PUBLIC DATA JSON api key 1
#PUBLIC DATA JSON api key 2

# Kakao Login
spring.security.oauth2.client.registration.kakao.client-id=02be7a608691cf6a46d575574798ecd7
spring.security.oauth2.client.registration.kakao.client-secret=df4bd507148728fb83df8909912f14b5
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id
#open AI
openai.api-key=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