spring.application.name=youth-policy-api

server.port=8080

logging.level.org.springframework.security=INFO


spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.url=jdbc:h2:tcp://localhost/~/EasyWork
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# MyBatis`
mybatis.configuration.map-underscore-to-camel-case=true
mybatis.mapper-locations=classpath:/mapper/*.xml
mybatis.type-aliases-package=org.sungsung.youthpolicy.domain
#always,never
spring.sql.init.mode=never
spring.sql.init.schema-locations=classpath:schema.sql


#PUBLIC DATA JSON api key 1
public.data.api.key: a08f16c3f1fa964e73d7f89c12d0ba23c237661b69c06b2b11143d8451c3a0de
#PUBLIC DATA JSON api key 2
publi.data.api.key2:33142eb1-009c-4456-bb7d-c7887f95bca8

#kakao Login
spring.security.oauth2.client.registration.kakao.client-id=0265347529f5a39baf17de2a1d30552e
spring.security.oauth2.client.registration.kakao.client-secret=olDAN8zm4Zs2r9n4RgQmVy4VijS7EfBU
spring.security.oauth2.client.registration.kakao.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}
spring.security.oauth2.client.registration.kakao.authorization-grant-type=authorization_code
spring.security.oauth2.client.registration.kakao.client-authentication-method=client_secret_post
spring.security.oauth2.client.registration.kakao.scope=profile_nickname,account_email
spring.security.oauth2.client.registration.kakao.client-name=Kakao

spring.security.oauth2.client.provider.kakao.authorization-uri=https://kauth.kakao.com/oauth/authorize
spring.security.oauth2.client.provider.kakao.token-uri=https://kauth.kakao.com/oauth/token
spring.security.oauth2.client.provider.kakao.user-info-uri=https://kapi.kakao.com/v2/user/me
spring.security.oauth2.client.provider.kakao.user-name-attribute=id